language: node_js
node_js:
- "stable"
cache: npm

install:
  - npm ci
cache:
  directories:
  - node_modules
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - npm run test

  after_script:
  - npm run coverage

notifications:
  email:false

